### ISSUE TITLE
Registered User - Manage Account Info

### ISSUE THREAD

**Issue by lucyfox4131** [lucyfox4131/the_pivot#7]
As a registered user who is logged in I can view my dashboard and have the option to click on update account. 

I can successfully update my account information. 

I will be redirected to my updated account information.

**Comment by lucyfox4131** [comment]
This functionality should already be complete.....

**Comment by AnnaCW** [comment]
User update functionality is already complete and tested in user_can_update_profile_spec.   (User sees flash message that updates have saved, rather than being redirected to account info).
